######################################################################
# Automatically generated by qmake (1.07a) Wed Nov 4 13:41:02 2009
######################################################################

TEMPLATE = app
DEPENDPATH += src ui
INCLUDEPATH += . src

# Input
HEADERS += src/globals.h src/XModelTree.h src/XModelView.h
INTERFACES += ui/XMMEMainWindow.ui \
              ui/XWidgetEditAgent.ui \
              ui/XWidgetEditDataType.ui \
              ui/XWidgetEditFile.ui \
              ui/XWidgetEditFunction.ui \
              ui/XWidgetEditFunctionInMessages.ui \
              ui/XWidgetEditFunctionOutMessages.ui \
              ui/XWidgetEditIOMessage.ui \
              ui/XWidgetEditMessage.ui \
              ui/XWidgetEditModel.ui \
              ui/XWidgetEditTimeUnit.ui \
              ui/XWidgetEditVariable.ui
SOURCES += src/main.cpp src/XModelTree.cpp src/XModelView.cpp
