######################################################################
# Automatically generated by qmake (1.07a) Wed Nov 4 14:17:55 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += globals.h \
           XMMEMainWindow.h \
           XModelTree.h \
           XModelView.h \
           XWidgetEditAgent.h \
           XWidgetEditDataType.h \
           XWidgetEditFile.h \
           XWidgetEditFunction.h \
           XWidgetEditFunctionInMessages.h \
           XWidgetEditFunctionOutMessages.h \
           XWidgetEditIOMessage.h \
           XWidgetEditMessage.h \
           XWidgetEditModel.h \
           XWidgetEditTimeUnit.h \
           XWidgetEditVariable.h
SOURCES += main.cpp XMMEMainWindow.cpp XModelTree.cpp XModelView.cpp
